#services:
#  app.user_repository:
#    class: App\Repository\UserRepository
#    factory: [ '@doctrine', getRepository ]
#    arguments:
#      - App:Web\Service
services:
  app.time_register_repository:
    class: App\Repository\TimeRegisterRepository
    factory: [ '@doctrine', getRepository ]
    arguments:
      - App\Entity\TimeRegister
