services:
  admin.user:
    class: App\Admin\UserAdmin
    tags:
      - { name: sonata.admin, model_class: App\Entity\User, manager_type: orm, label: 'Usuaris', group: 'General' }
    arguments: [ null, App\Entity\User,null, "@security.user_password_hasher" ]
